// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9k_6i94Hapz_MS1eg1xOSB97Nk8Nivgc',
    appId: '1:225378996225:web:53511b8f54470d6a953000',
    messagingSenderId: '225378996225',
    projectId: 'flutterweb-968c2',
    authDomain: 'flutterweb-968c2.firebaseapp.com',
    databaseURL: 'https://flutterweb-968c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterweb-968c2.appspot.com',
    measurementId: 'G-2WNH4Q5C97',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Vd56LKIM8ONOj4Bu7QoHXO-cp6gZYTk',
    appId: '1:225378996225:ios:a89d07faf252b7b6953000',
    messagingSenderId: '225378996225',
    projectId: 'flutterweb-968c2',
    databaseURL: 'https://flutterweb-968c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterweb-968c2.appspot.com',
    iosClientId: '225378996225-hr85c5n9nrc5j881jbid9beaf1uuknm6.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Vd56LKIM8ONOj4Bu7QoHXO-cp6gZYTk',
    appId: '1:225378996225:ios:1e000bd9f1a52e75953000',
    messagingSenderId: '225378996225',
    projectId: 'flutterweb-968c2',
    databaseURL: 'https://flutterweb-968c2-default-rtdb.firebaseio.com',
    storageBucket: 'flutterweb-968c2.appspot.com',
    iosClientId: '225378996225-t9kgkp114ds1cjfvd0pn9tdp5a3el4lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirestore.RunnerTests',
  );
}
